export { default as About } from "./About";
export { default as PrivacyPolicy } from "./PrivacyPolicy";
export { default as Home } from "./Home";
export { default as Services } from "./Services";
export { default as Team } from "./Team";
export { default as Appointment } from "./Appointment";
export { default as FAQ } from "./FAQ";
export { default as Contact } from "./Contact";
export { default as PersonalDataProtection } from "./PersonalDataProtection";